export const STORE_GLOBAL_CODES = "STORE_GLOBAL_CODES";
export const STORE_SIDEBAR = "STORE_SIDEBAR";
export const STORE_HEADER_MODAL = "STORE_HEADER_MODAL";
export const STORE_TENANT_DETAIL = "STORE_TENANT_DETAIL";
export const STORE_LOADING = "STORE_LOADING";
